const fs = require("fs");
const assert = require("assert");

const app = fs.readFileSync("app.js", "utf8");
const inspector = fs.readFileSync("smart_data_loader.js", "utf8");
const auxiliary = fs.readFileSync("auxiliary_mode.js", "utf8");

assert.match(app, /classifyReportFiles\(candidates\)/);
assert.match(app, /idle: \["detail", "driverMetricsDetail", "driverDetails", "rolling7Day"\]/);
assert.match(inspector, /xlsxThreshold/);
assert.match(inspector, /roleQualifies/);
assert.match(auxiliary, /routes\.detail && routes\.driverDetails && routes\.rolling7Day/);
assert.match(auxiliary, /item\.slice\(10\)/, "rolling idle bridge must skip the week-start date column");
assert.equal((app.match(/analyzeApu\(apuWorkbookRows\(workbooks\.apu\), drivers, files\.apu \|\| null\)/g) || []).length, 2, "basic and idle modes must both pass the routed APU workbook to the parser");
assert.match(app, /function apuWorkbookRows\(workbook\)[\s\S]*for \(const sheetName of workbook\.SheetNames\)[\s\S]*findApuHeaderRow\(rows\) >= 0/, "APU parsing must inspect every worksheet for its header row");
assert.match(app, /function ptaDriverCode\(fullName, driverCode = ""\)[\s\S]*last\.slice\(0, 7\)[\s\S]*slice\(0, 8\)/, "PTA driver codes must use up to seven surname characters plus the first-name initial, capped at eight characters");
assert.equal((app.match(/attachDriverTruckAssignments\(drivers, pta, apu(?:, assignmentEvidence)?\);/g) || []).length, 3, "every report mode must attach PTA and APU truck assignments to drivers");
assert.match(app, /function driverAssignmentLabel\(driver\)[\s\S]*\$\{driver\.assignedTruck\} — \$\{name\}/, "linked trucks and drivers must remain one operational assignment in the UI without a redundant Truck prefix");
assert.match(app, /truck: driver\.assignedTruck \|\| ""/, "driver follow-up notes must retain their matched truck for handoff grouping");
assert.match(app, /limitDatedHistory\(record\.history, 7, reportDate\)/, "rolling 7-day output must discard data outside the latest seven calendar days");
assert.match(app, /limitDatedHistory\(history, 28, reportDate\)/, "rolling 28-day output must discard data outside the latest 28 calendar days");
assert.match(app, /const highIdleDriverCount = idleEligibleRecords\.filter/, "the overview indicator must count unified eligible driver and truck records over 50% rolling 7-day idle");
assert.doesNotMatch(app, /modalMetric\("Possible yearly cost"/, "the unused yearly-cost driver card must be removed");
assert.match(app, /drivers\.fleetIdle7DayPct = rolling7\.fleetIdle7DayPct \?\? null/, "the dashboard must preserve the rolling 7-day report Grand Total");
assert.match(app, /drivers\.fleetIdle28DayPct = metrics\.fleetIdle28DayPct \?\? rolling28\.fleetIdle28DayPct \?\? null/, "the dashboard must prefer the report's weighted rolling 4-week Grand Total");
assert.match(app, /const idle28Average = idle28Totals\.engine > 0 \? idle28Totals\.idle \/ idle28Totals\.engine/, "the KPI must recompute a weighted idle percentage after exclusions");
assert.match(app, /function splitNotesByAge\(notes, now = Date\.now\(\)\)[\s\S]*now - 7 \* 86400000/, "card notes older than seven days must be separated without deletion");
assert.match(app, /data-older-notes-toggle="pta"[\s\S]*data-older-notes-toggle="driver"/, "both truck and driver note cards must provide older-note toggles");
assert.doesNotMatch(app, /const emptyApu = analyzeApu\(\[\], drivers, null\)/, "basic mode must not discard routed APU data");
console.log("Content discovery and partial-idle bridge smoke test passed.");
